DuLich/DuLichUI/Controllers/Admin/DestinationController.cs
using APIIntegration.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace DuLichUI.Controllers.Admin
{
    [Route("~/admin/destination")]
    [Authorize(Roles = "0")]
    public class DestinationController : Controller
    {
        private readonly IDestinationAPI _destinationAPI;

        public DestinationController(IDestinationAPI destinationAPI)
        {
            _destinationAPI = destinationAPI;
        }

        public async Task<IActionResult> Index()
        {
            var destinations = await _destinationAPI.GetAll();
            return View("../Admin/Destination/Index", destinations);
        }

        [Route("toggle/{id}")]
        public async Task<IActionResult> Toggle(int id)
        {
            await _destinationAPI.Toggle(id, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return RedirectToAction("Index");
        }
    }
}

DuLich/DuLichUI/Controllers/DestinationController.cs
using APIIntegration.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ViewModel.Models;
using ViewModel.ModelsView;
using ViewModel.Request.DiemThamQuan;
using ViewModel.Request.NhaHang;

namespace DuLichUI.Controllers
{
    [Authorize]
    public class DestinationController : Controller
    {
        private IDestinationAPI _destinationAPI;
        private IUserAPI _userAPI;

        public DestinationController(IDestinationAPI destinationAPI, IUserAPI userAPI)
        {
            _destinationAPI = destinationAPI;
            _userAPI = userAPI;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var id = HttpContext.Session.GetString("UserId");
                var destinations = await _destinationAPI.GetDiemThamQuanByOwner(int.Parse(id), "Bearer " + HttpContext.Session.GetString("BearerToken"));
                ViewData["destinations"] = destinations;
                var temp = HttpContext.Session.GetString("User");
                if (temp != null)
                {
                    var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                    var x = await _userAPI.GetById(user.Id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
                    ViewData["user"] = x;
                }
                return View();
            }
            catch
            {
                ViewData["destinations"] = new List<DiemThamQuan>();
                return View();
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
            var dest = await _destinationAPI.GetById(id);
            if (!dest.TrangThai)
            {
                return Redirect("/destination/list");
            }
            ViewData["dtqs"] = await _destinationAPI.GetAll();
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
                ViewData["UserId"] = HttpContext.Session.GetString("UserId");
            return View(dest);
        }

        [AllowAnonymous]
        public async Task<IActionResult> List()
        {
            var dtqs = await _destinationAPI.GetAll();
            return View(dtqs);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Search([FromQuery] TimKiemDiemThamQuanRequest request)
        {
            var dtqs = await _destinationAPI.SearchDiemThamQuan(request);
            return View("List", dtqs);
        }

        public async Task<IActionResult> Create()
        {
            var temp = HttpContext.Session.GetString("User");
            if (temp != null)
            {
                var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                var x = await _userAPI.GetById(user.Id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
                ViewData["user"] = x;
            }
            return View(new ThemDiemThamQuanRequest());
        }

        public async Task<IActionResult> Edit(int id)
        {
            var destination = await _destinationAPI.GetById(id);
            return View(destination);
        }

        [HttpPost]
        public async Task<IActionResult> EditDiemThamQuan([FromForm] ChinhSuaDiemThamQuanRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", request);
            }
            await _destinationAPI.EditDiemThamQuan(request, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return Redirect("/destination");
        }

        [HttpPost]
        public async Task<IActionResult> CreateDiemThamQuan([FromForm] ThemDiemThamQuanRequest request)
        {
            if (!ModelState.IsValid)
            {
                var temp = HttpContext.Session.GetString("User");
                if (temp != null)
                {
                    var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                    var x = await _userAPI.GetById(user.Id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
                    ViewData["user"] = x;
                }
                return View("Create", request);
            }
            await _destinationAPI.CreateDiemThamQuan(request, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return Redirect("/destination");
        }

        [HttpPost]
        public async Task<IActionResult> CreateBinhLuan([FromForm] BinhLuanDiemThamQuanVM request)
        {
            await _destinationAPI.BinhLuanDiemThamQuan(request, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return Redirect("/destination/detail/" + request.IdDiemThamQuan);
        }
    }
}

DuLich/DuLichUI/Views/Destination/Create.cshtml
@using ViewModel.Models;
@using ViewModel.Request.DiemThamQuan;
@model ThemDiemThamQuanRequest;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Tạo điểm tham quan";
    NguoiDung user = ViewData["user"] as NguoiDung;
}
<style>
    body {
        margin-top: 20px;
        background-color: #f2f6fc;
        color: #69707a;
    }

    .img-account-profile {
        height: 10rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }

        .card .card-header {
            font-weight: 500;
        }

    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }

    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }

    .form-control, .dataTable-input {
        display: block;
        width: 100%;
        padding: 0.875rem 1.125rem;
        font-size: 0.875rem;
        font-weight: 400;
        line-height: 1;
        color: #69707a;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #c5ccd6;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.35rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }

    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }
</style>
<div class="container-xxl px-4 mt-4">
    <a href="/destination"><button type="button" class="btn btn-primary mb-3">Quay lại</button></a>
    <hr class="mt-0 mb-4">
    <div class="">
        <div class="card mb-4">
            <div class="card-header">Chi tiết điểm tham quan</div>
            <div class="card-body">
                <form asp-action="CreateDiemThamQuan" asp-controller="Destination" method="post" enctype="multipart/form-data">
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Ảnh đại diện</label>
                            <input asp-for="@Model.AnhDaiDien" />
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Ảnh chi tiết</label>
                            <input asp-for="@Model.AnhChiTiet" />
                        </div>
                    </div>
                    <input hidden name="chuDichVu" value="@user.Id"/>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label  class="small mb-1">Tên điểm tham quan</label>
                            <input  class="form-control" asp-for="@Model.TenDiaDiem"/>
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Địa điểm</label>
                            <input class="form-control" asp-for="@Model.DiaDiem" />
                        </div>
                    </div>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Mô tả</label>
                            <textarea class="form-control" asp-for="@Model.MoTaDichVu"></textarea>
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Giá dịch vụ</label>
                            <input class="form-control" asp-for="@Model.Gia" />
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Tạo mới</button>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#loader').addClass('d-none');
        });
    </script>
}

DuLich/DuLichUI/Views/Destination/Edit.cshtml
@using ViewModel.Models;
@using ViewModel.Request.Tour;
@model DiemThamQuan;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Chỉnh sửa điểm tham quan";
}
<style>
    body {
        margin-top: 20px;
        background-color: #f2f6fc;
        color: #69707a;
    }

    .img-account-profile {
        height: 10rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }

        .card .card-header {
            font-weight: 500;
        }

    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }

    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }

    .form-control, .dataTable-input {
        display: block;
        width: 100%;
        padding: 0.875rem 1.125rem;
        font-size: 0.875rem;
        font-weight: 400;
        line-height: 1;
        color: #69707a;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #c5ccd6;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.35rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }

    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }
</style>
<div class="container-xxl px-4 mt-4">
    <a href="/destination"><button type="button" class="btn btn-primary mb-3">Quay lại</button></a>
    <hr class="mt-0 mb-4">
    <div class="row">
        <div class="col-xl-4">
            <div class="card mb-4 mb-xl-0">
                <div class="card-header">Ảnh minh hoạ</div>
                <div class="card-body text-center">
                    <img class="img-account-profile rounded-circle mb-2" src="@Model?.AnhDaiDien" alt="">
                </div>
            </div>
            <div class="card mb-4 mb-xl-0">
                <div class="card-header">Ảnh chi tiết</div>
                <div class="card-body text-center">
                    <img class="img-account-profile rounded-circle mb-2" src="@Model?.DiemThamQuanCT?.AnhChiTiet" alt="">
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <div class="card mb-4">
            <div class="card-header">Chi tiết điểm tham quan</div>
            <div class="card-body">
                    <form asp-action="EditDiemThamQuan" asp-controller="Destination" method="post" enctype="multipart/form-data">
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Ảnh minh hoạ</label>
                                <input type="file" name="AnhDaiDien" />
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Hình ảnh</label>
                                <input type="file" name="AnhChiTiet" />
                        </div>
                    </div>
                    <input hidden asp-for="@Model.ChuDichVu" />
                    <input hidden asp-for="@Model.Id" />
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Tên tour</label>
                            <input class="form-control" asp-for="@Model.TenDiaDiem" />
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Địa điểm</label>
                            <input class="form-control" asp-for="@Model.DiaDiem" />
                        </div>
                    </div>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Mô tả</label>
                            <textarea class="form-control" name="MoTaDichVu">@Model?.DiemThamQuanCT?.MoTaDichVu</textarea>
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Giá</label>
                            <input class="form-control" asp-for="@Model.Gia" />
                        </div>
                    </div>
                    
                    <button class="btn btn-primary" type="submit">Cập nhật</button>
                </form>
            </div>
        </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#loader').addClass('d-none');
        });
    </script>
}

DuLich/DuLichUI/Views/Destination/Index.cshtml
@using ViewModel.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Quản lý điểm tham quan";
    List<DiemThamQuan> dtqs = (List<DiemThamQuan>)ViewData["destinations"];
    NguoiDung user = ViewData["user"] as NguoiDung;
}
<div class="container-xl px-4 mt-4">
    <!-- Account page navigation-->
    <nav class="nav nav-borders">
        <a class="nav-link" href="/user">Profile</a>
        <a class="nav-link" href="/user/order">Đơn hàng của tôi</a>
        @if (user.PhanQuyen == 2)
        {
            <a class="nav-link" href="/user/guestorder">Đơn hàng của khách</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("0"))
        {
            <a class="nav-link" href="/tour">Quản lý tour</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("1"))
        {
            <a class="nav-link" href="/hotel">Quản lý khách sạn</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("2"))
        {
            <a class="nav-link" href="/delivery">Quản lý vận chuyển</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("3"))
        {
            <a class="nav-link" href="/restaurant">Quản lý nhà hàng</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("4"))
        {
            <a class="nav-link active ms-0" href="/destination">Quản lý điểm tham quan</a>
        }
    </nav>
    <hr class="mt-0 mb-4">
    <div class=" bg-white p-5">
        <a href="/destination/create">
            <button type="button" class="btn btn-primary mb-3">Thêm điểm tham quan</button>
        </a>
        <table id="dataTable" class="table table-bordered  dataTable">
            <thead>
                <tr class="text-center">
                    <th style="text-align: center; width: 5%">Mã</th>
                    <th style="text-align: center; width: 20%">Tên điểm tham quan </th>
                    <th style="text-align: center; width: 5%">Địa điểm </th>
                    <th style="text-align: center; width: 10%">Giá</th>
                    <th style="text-align: center; width: 10%">Lượt đánh giá </th>
                    <th style="text-align: center; width: 20%">Thao tác </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var dtq in dtqs)
                {
                    <tr>
                        <td class="text-center">@dtq.Id</td>
                        <td class="text-center">@dtq.TenDiaDiem</td>
                        <td class="text-center">@dtq.DiaDiem</td>
                        <td class="text-center">@dtq.Gia</td>
                        <td class="text-center">@dtq.DiemThamQuanCT.DanhGia</td>
                        <td class="text-center">
                            <a href="/destination/edit/@dtq.Id" class="btn btn-success">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

DuLich/DuLichUI/Views/Destination/List.cshtml
@using ViewModel.Models;
@model List<DiemThamQuan>;
@{
    ViewData["Title"] = "Danh sách điểm tham quan";
}
<nav class="breadcrumb-nav d-flex align-items-center" aria-label="breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="under" href="/">Home</a></li>
            <li class="breadcrumb-item"><a class="under" href="/destination/list">Điểm tham quan</a></li>
        </ol>
    </div>
</nav>
<div class="page-content">
    <div class="container">
        <div class="row">
            <aside class="sidebar col-lg-3 order-1 order-lg-0">
                <div class="sidebar__content js-sticky-top">
                    <div class="sidebar-filter modal card fade" id="sidebarFilter" tabindex="-1" role="dialog">
                        <button class="btn-toggle btn btn-light" type="button" data-dismiss="modal"><span class="icon-bar"></span></button>
                        <div class="modal-header bg-white">
                            <h4 class="modal-title">Lọc</h4>
                        </div>
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <ul class="sidebar-filter__list">
                                        <li class="sidebar-filter__item">
                                            <h5 class="sidebar-filter__title"><a class="sidebar-filter__toggle d-flex justify-content-between align-items-center" href="#price" data-toggle="collapse" role="button"><span>Giá</span><i class="fa fa-angle-down"></i></a></h5>
                                            <div class="collapse show" id="price">
                                                <div class="sidebar-filter__content">
                                                    <label class="custom-control custom-checkbox">
                                                        <input class="custom-control-input" type="checkbox" /><span class="custom-control-label pointer">50000 - 99000 VND</span>
                                                    </label>
                                                    <label class="custom-control custom-checkbox">
                                                        <input class="custom-control-input" type="checkbox" /><span class="custom-control-label pointer">100000 - 149000 VND</span>
                                                    </label>
                                                    <label class="custom-control custom-checkbox">
                                                        <input class="custom-control-input" type="checkbox" /><span class="custom-control-label pointer">150000 - 199000 VND</span>
                                                    </label>
                                                    <label class="custom-control custom-checkbox">
                                                        <input class="custom-control-input" type="checkbox" /><span class="custom-control-label pointer">200000 VND +</span>
                                                    </label>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </aside>
            <div class="col-lg-9 category-content">
                <nav class="sortbar navbar shadow-sm d-flex align-items-stretch">
                    <div class="sortbar__title d-flex align-items-stretch">
                        <button class="navbar-brand d-flex align-items-center pointer js-toggle-sidebar" data-target="#sidebarFilter" data-toggle="modal" type="button"><i class="d-lg-none icon icon-filter"></i><span class="ml-2 d-none d-lg-inline">Sắp xếp:</span></button>
                    </div>
                    <div class="sortbar__sort js-sorting d-flex align-items-stretch"><a class="nav-link" href="#">Độ nổi tiếng</a><a class="nav-link" href="#">Giá</a><a class="nav-link" href="#">Đánh giá</a><a class="nav-link d-flex d-md-none align-items-center" href="#"><span class="mr-2">Đánh giá</span><i class="icon icon-sort-duble"></i></a></div>
                    <div class="sortbar__grid d-flex align-items-stretch ml-md-auto"><a class="nav-link active js-toggle-grid" href="#" data-grid="grid" data-cols="col-12 col-sm-6 col-xl-4 d-flex"><i class="icon icon-grid"></i></a><a class="nav-link js-toggle-grid" href="#" data-grid="list" data-cols="col-12 d-flex"><i class="icon icon-list-mb"></i></a></div>
                </nav>
                <div class="category-content__items row pad-lg-20">
                    @foreach(var item in Model)
                    {
                        if (!item.TrangThai) continue;

                        <div class="col-12 col-sm-6 col-xl-4 d-flex">
                            <div class="product bg-white js-grid-item">
                                <div class="product__special bg-primary text-white">
                                    Ưu đãi
                                </div><a class="product__img-top d-block" href="/destination/detail/@item?.Id"><img class="img-fluid" src="@item?.AnhDaiDien" alt="#" /></a>
                                <div class="product__body">
                                    <h4 class="product__title"><a href="/destination/detail/@item?.Id">@item?.TenDiaDiem</a></h4>
                                    <div class="product__rating mb-2">
                                        <div class="rating">
                                            <select class="js-rating-stat" data-current-rating="@item?.DiemThamQuanCT.DanhGia">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                    </div>
                                    <ul class="product__stat d-flex flex-wrap justify-content-between align-items-center">
                                        <li class="mr-3"><span>@item?.DiaDiem</span></li>
                                        @{
                                            int.TryParse(item.DiemThamQuanCT.DanhGia, out int danhgia);
                                        }
                                        <li class="d-inline-flex align-items-center"><i class="icon icon-thumbs-up mr-1"></i><span>@(danhgia * 2)/10</span></li>
                                    </ul>
                                    <hr />
                                    <ul class="product__price d-flex justify-content-between align-items-center">
                                        <li class="mr-2"><span>Giá</span></li>
                                        <li>
                                            <span class="cost">@item.Gia VND</span>
                                        </li>
                                    </ul>
                                    <hr />
                                    <div class="product__desc">
                                        <p>@item.DiemThamQuanCT.MoTaDichVu</p><a class="product__link-more" href="/destenation/detail/@item?.Id">Xem thêm</a>
                                    </div>
                                </div>
                                <hr class="d-none d-sm-block" />
                                <div class="product__footer">
                                    <ul class="product__price d-flex justify-content-between align-items-center">
                                        <li class="mr-2"><span>Giá</span></li>
                                        <li>
                                            <span class="cost">@item?.Gia VND</span>
                                        </li>
                                    </ul><a class="product__btn-book btn btn-secondary btn--round" href="booking-traveler.html">book now</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <button class="btn btn-primary btn-nav btn-nav--up js-scroll-up" type="button"><i class="fa fa-angle-up"></i></button>
</div>