DuLich/DuLichUI/Controllers/Admin/TourController.cs
using APIIntegration.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace DuLichUI.Controllers.Admin
{
    [Route("~/admin/tour")]
    [Authorize(Roles = "0")]
    public class TourController : Controller
    {
        private readonly ITourAPI _tourAPI;

        public TourController(ITourAPI tourAPI)
        {
            _tourAPI = tourAPI;
        }

        public async Task<IActionResult> Index()
        {
            var tours = await _tourAPI.GetAll();
            return View("../Admin/Tour/Index", tours);
        }

        [Route("toggle/{id}")]
        public async Task<IActionResult> Toggle(int id)
        {
            await _tourAPI.Toggle(id, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return RedirectToAction("Index");
        }
    }
}

DuLich/DuLichUI/Controllers/TourController.cs
using APIIntegration.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RestEase.Implementation;
using System.Linq.Expressions;
using ViewModel.Models;
using ViewModel.ModelsView;
using ViewModel.Request.Tour;

namespace DuLichUI.Controllers
{
    [Authorize]
    public class TourController : Controller
    {
        private ITourAPI _tourAPI;
        private IUserAPI _userAPI;

        public TourController(ITourAPI tourAPI, IUserAPI userAPI)
        {
            _tourAPI = tourAPI;
            _userAPI = userAPI;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var id = HttpContext.Session.GetString("UserId");
                var tours = await _tourAPI.GetTourByOwner(int.Parse(id), "Bearer " + HttpContext.Session.GetString("BearerToken"));
                ViewData["tours"] = tours;
                var temp = HttpContext.Session.GetString("User");
                if (temp != null)
                {
                    var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                    var x = await _userAPI.GetById(user.Id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
                    ViewData["user"] = x;
                }
                return View();
            }
            catch
            {
                ViewData["tours"] = new List<Tour>();
                return View();
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
            var tour = await _tourAPI.GetById(id);
            if (!tour.TrangThai)
            {
                return Redirect("/tour/list");
            }
            ViewData["tours"] = await _tourAPI.GetAll();
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
                ViewData["UserId"] = HttpContext.Session.GetString("UserId");
            return View(tour);
        }

        public async Task<IActionResult> Booking(int id)
        {
            var tour = await _tourAPI.GetById(id);
            if (!tour.TrangThai)
            {
                return Redirect("/tour/list");
            }
            var temp = HttpContext.Session.GetString("User");
            if (temp != null)
            {
                var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                var x = await _userAPI.GetById(user.Id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
                ViewData["user"] = x;
            }
            return View(tour);
        }

        [HttpPost]
        public async Task<IActionResult> CreateBooking([FromForm] DatTourRequest request)
        {
            var tour = await _tourAPI.GetById(request.IdTour);
            if (!tour.TrangThai)
            {
                return Redirect("/tour/list?order=false");
            }
            var temp = HttpContext.Session.GetString("User");
            if (temp != null)
            {
                var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                request.IdNguoiDung = user.Id;
            }
            await _tourAPI.DatTour(request, "Bearer " + HttpContext.Session.GetString("BearerToken"));
            return Redirect("/tour/list?order=true");
        }

        [AllowAnonymous]
        public async Task<IActionResult> List()
        {
            var tours = await _tourAPI.GetAll();
            return View(tours);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Search([FromQuery] TimKiemTourRequest request)
        {
            var tours = await _tourAPI.SearchTour(request);
            return View("List", tours);
        }

        public async Task<IActionResult> Create()
        {
            var temp = HttpContext.Session.GetString("User");
            if (temp != null)
            {
                var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                var x = await _userAPI.GetById(user.Id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
                ViewData["user"] = x;
            }
            return View(new ThemTourRequest());
        }

        public async Task<IActionResult> Edit(int id)
        {
            var tour = await _tourAPI.GetById(id);
            return View(tour);
        }

        [HttpPost]
        public async Task<IActionResult> EditTour([FromForm] ChinhSuaTourRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", request);
            }
            await _tourAPI.EditTour(request, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return Redirect("/tour");
        }

        [HttpPost]
        public async Task<IActionResult> CreateTour([FromForm] ThemTourRequest request)
        {
            if (!ModelState.IsValid)
            {
                var temp = HttpContext.Session.GetString("User");
                if (temp != null)
                {
                    var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                    var x = await _userAPI.GetById(user.Id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
                    ViewData["user"] = x;
                }
                return View("Create", request);
            }
            await _tourAPI.CreateTour(request, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return Redirect("/tour");
        }

        [HttpPost]
        public async Task<IActionResult> CreateBinhLuan([FromForm] BinhLuanTourVM request)
        {
            await _tourAPI.BinhLuanTour(request, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return Redirect("/tour/detail/" + request.IdTour);
        }
    }
}

DuLich/DuLichUI/Views/Tour/Booking.cshtml
@using ViewModel.Models;
@model Tour;

@{
    ViewData["Title"] = "Đặt tour";
    var user = ViewData["user"] as NguoiDung;
}

<nav class="breadcrumb-nav d-flex align-items-center" aria-label="breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="under" href="/">Home</a></li>
            <li class="breadcrumb-item"><a class="under" href="/tour/list">Tour du lịch</a></li>
        </ol>
    </div>
</nav>
<div class="page-content">
    <div class="container">
        <div class="row">
            <aside class="sidebar col-lg-3 order-1 order-lg-0">
                <div class="sidebar__content js-sticky-top">
                    <section class="sidebar__card card">
                        <div class="sidebar__card-title">
                            <h4 class="card-title mb-1">@Model?.TenTour</h4>
                            <ul class="sidebar__card-meta d-flex align-items-center">
                                <li>
                                    <div class="rating">
                                        <select class="js-rating-stat" data-current-rating="@Model?.LuotDanhGia">
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                        </select>
                                    </div>
                                </li>
                                <li class="likes ml-auto text-nowrap"><i class="mr-1 icon icon-thumbs-up"></i><span>@(Model?.LuotDanhGia * 2)/10</span></li>
                            </ul>
                            <hr class="my-3 mt-2" />
                        </div>
                        <ul class="sidebar__payment">
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Số ngày</div>
                                <ul>
                                    <li>@Model.SoNgay ngày</li>
                                </ul>
                            </li>
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Ngày bắt đầu</div>
                                <ul>
                                    <li>@Model.NgayBatDau.ToString()</li>
                                </ul>
                            </li>
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Ngày kết thúc</div>
                                <ul>
                                    <li>@Model?.NgayKetThuc.ToString()</li>
                                </ul>
                            </li>
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Địa điểm</div>
                                <ul>
                                    <li>@Model?.TourCT?.DiaDiem</li>
                                </ul>
                            </li>
                        </ul>
                        <hr class="mt-2">
                        <ul class="sidebar__payment-total">
                            <li class="h4 fw-bold f-primary mb-0">Giá: @Model.GiaTour VND</li>
                        </ul>
                    </section>
                </div>
            </aside>
            <div class="col-lg-9 d-flex" id="barba-wrapper">
                <div class="barba-container">
                    <div class="booking-card card">
                        <div class="card-body">
                            <div class="booking-card__title">
                                <h2>Thông tin đặt hàng</h2>
                                <hr class="mb-4">
                            </div>
                            <form class="booking-card__form" asp-action="CreateBooking" asp-controller="Tour" method="POST">
                                <input hidden name="IdTour" value="@Model.Id" />
                                <div class="row pad-lg-20">
                                    <div class="form-group col-12 col-lg-6">
                                        <label asp-for="@user.HoTen">Họ và tên</label>
                                        <input class="form-control" asp-for="@user.HoTen" readonly/>
                                    </div>
                                    <div class="form-group col-12 col-lg-6 col-xl-4">
                                        <label asp-for="@user.Sdt">Số điện thoại</label>
                                        <input class="form-control" asp-for="@user.Sdt" readonly />
                                    </div>
                                    <div class="form-group col-12 col-lg-6 col-xl-4">
                                        <label asp-for="@user.Email"></label>
                                        <input class="form-control" asp-for="@user.Email" readonly />
                                    </div>
                                    <div class="form-group col-12 col-lg-6 col-xl-4">
                                        <label asp-for="@user.NoiO">Nơi ở</label>
                                        <input class="form-control" asp-for="@user.NoiO" readonly />
                                    </div>
                                    <div class="form-group col-12 col-lg-6 col-xl-4">
                                        <label asp-for="@user.CCCD">Căn cước công dân</label>
                                        <input class="form-control" asp-for="@user.CCCD" readonly />
                                    </div>
                                </div>
                                <div class="d-flex">
                                    <button class="btn btn-secondary btn--round mx-auto ml-sm-0" type="submit">
                                        Booking
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <button class="btn btn-primary btn-nav btn-nav--up js-scroll-up" type="button"><i class="fa fa-angle-up"></i></button>
</div>

DuLich/DuLichUI/Views/Tour/Create.cshtml
@using ViewModel.Models;
@using ViewModel.Request.Tour;
@model ThemTourRequest;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Tạo tour";
    NguoiDung user = ViewData["user"] as NguoiDung;
}
<style>
    body {
        margin-top: 20px;
        background-color: #f2f6fc;
        color: #69707a;
    }

    .img-account-profile {
        height: 10rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }

        .card .card-header {
            font-weight: 500;
        }

    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }

    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }

    .form-control, .dataTable-input {
        display: block;
        width: 100%;
        padding: 0.875rem 1.125rem;
        font-size: 0.875rem;
        font-weight: 400;
        line-height: 1;
        color: #69707a;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #c5ccd6;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.35rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }

    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }
</style>
<div class="container-xxl px-4 mt-4">
    <a href="/tour"><button type="button" class="btn btn-primary mb-3">Quay lại</button></a>
    <hr class="mt-0 mb-4">
    <div class="">
        <div class="card mb-4">
            <div class="card-header">Chi tiết Tour</div>
            <div class="card-body">
                <form asp-action="CreateTour" asp-controller="Tour" method="post" enctype="multipart/form-data">
                    <div class="col-md-6">
                        <label class="small mb-1">Hình ảnh</label>
                        <input asp-for="@Model.HinhAnhTour" />
                    </div>
                    <input hidden name="chuTour" value="@user.Id"/>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-4">
                            <label  class="small mb-1">Tên tour</label>
                            <input  class="form-control" asp-for="@Model.TenTour"/>
                        </div>
                        <div class="col-md-4">
                            <label  class="small mb-1">Số ngày</label>
                            <input  class="form-control" asp-for="@Model.SoNgay" />
                        </div>
                        <div class="col-md-4">
                            <label class="small mb-1">Địa điểm</label>
                            <input class="form-control" asp-for="@Model.DiaDiem" />
                        </div>
                    </div>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Mô tả</label>
                            <textarea class="form-control" asp-for="@Model.MoTaTour"></textarea>
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Chi tiết</label>
                            <textarea class="form-control" asp-for="@Model.ChiTietTour"></textarea>
                        </div>
                    </div>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Giá khuyến mãi</label>
                            <input class="form-control" asp-for="@Model.KhuyenMaiTour" />
                        </div>
                        <div class="col-md-6">
                            <label  class="small mb-1">Giá gốc</label>
                            <input  class="form-control" asp-for="@Model.GiaTour" />
                        </div>
                    </div>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label  class="small mb-1">Ngày bắt đầu</label>
                            <input  class="form-control" asp-for="@Model.NgayBatDau" />
                        </div>
                        <div class="col-md-6">
                            <label  class="small mb-1">Ngày kết thúc</label>
                            <input  class="form-control" asp-for="@Model.NgayKetThuc" />
                        </div>
                    </div>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Lịch trình</label>
                            <textarea class="form-control" asp-for="@Model.LichTrinhNgay"></textarea>
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1" >Chi tiết lịch trình</label>
                            <textarea class="form-control" asp-for="@Model.ChiTietLichTrinh"></textarea>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Tạo mới</button>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#loader').addClass('d-none');
        });
    </script>
}

DuLich/DuLichUI/Views/Tour/Edit.cshtml
@using ViewModel.Models;
@using ViewModel.Request.Tour;
@model Tour;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Chỉnh sửa tour";
}
<style>
    body {
        margin-top: 20px;
        background-color: #f2f6fc;
        color: #69707a;
    }

    .img-account-profile {
        height: 10rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }

        .card .card-header {
            font-weight: 500;
        }

    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }

    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }

    .form-control, .dataTable-input {
        display: block;
        width: 100%;
        padding: 0.875rem 1.125rem;
        font-size: 0.875rem;
        font-weight: 400;
        line-height: 1;
        color: #69707a;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #c5ccd6;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.35rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }

    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }
</style>
<div class="container-xxl px-4 mt-4">
    <a href="/tour"><button type="button" class="btn btn-primary mb-3">Quay lại</button></a>
    <hr class="mt-0 mb-4">
    <div class="row">
        <div class="col-xl-4">
            <div class="card mb-4 mb-xl-0">
                <div class="card-header">Ảnh minh hoạ</div>
                <div class="card-body text-center">
                    <img class="img-account-profile rounded-circle mb-2" src="@Model?.HinhAnhTour" alt="">
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <div class="card mb-4">
            <div class="card-header">Chi tiết Tour</div>
            <div class="card-body">
                <form asp-action="EditTour" asp-controller="Tour" method="post" enctype="multipart/form-data">
                    <div class="col-md-6">
                        <label class="small mb-1">Hình ảnh</label>
                        <input type="file" name="HinhAnhTour" />
                    </div>
                    <input hidden asp-for="@Model.ChuTour" />
                    <input hidden asp-for="@Model.Id" />
                    <div class="row gx-3 mb-3">
                        <div class="col-md-4">
                            <label class="small mb-1">Tên tour</label>
                            <input class="form-control" asp-for="@Model.TenTour" />
                        </div>
                        <div class="col-md-4">
                            <label class="small mb-1">Số ngày</label>
                            <input class="form-control" asp-for="@Model.SoNgay" />
                        </div>
                        <div class="col-md-4">
                            <label class="small mb-1">Địa điểm</label>
                            <input class="form-control" value="@Model.TourCT.DiaDiem" name="DiaDiem" />
                        </div>
                    </div>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Mô tả</label>
                            <textarea class="form-control" asp-for="@Model.MoTaTour"></textarea>
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Chi tiết</label>
                            <textarea class="form-control" asp-for="@Model.ChiTietTour"></textarea>
                        </div>
                    </div>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Giá khuyến mãi</label>
                            <input class="form-control" asp-for="@Model.KhuyenMaiTour" />
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Giá gốc</label>
                            <input class="form-control" asp-for="@Model.GiaTour" />
                        </div>
                    </div>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Ngày bắt đầu</label>
                            <input class="form-control" asp-for="@Model.NgayBatDau" />
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Ngày kết thúc</label>
                            <input class="form-control" asp-for="@Model.NgayKetThuc" />
                        </div>
                    </div>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Lịch trình</label>
                            <textarea class="form-control" name="LichTrinhNgay">@Model.TourCT.LichTrinhNgay</textarea>
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Chi tiết lịch trình</label>
                            <textarea class="form-control" name="ChiTietLichTrinh">@Model.TourCT.ChiTietLichTrinh</textarea>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Cập nhật</button>
                </form>
            </div>
        </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#loader').addClass('d-none');
        });
    </script>
}

DuLich/DuLichUI/Views/Tour/Index.cshtml
@using ViewModel.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Quản lý tour";
    List<Tour> tours = (List<Tour>)ViewData["tours"];
    NguoiDung user = ViewData["user"] as NguoiDung;
}
<div class="container-xl px-4 mt-4">
    <!-- Account page navigation-->
    <nav class="nav nav-borders">
        <a class="nav-link" href="/user">Profile</a>
        <a class="nav-link" href="/user/order">Đơn hàng của tôi</a>
        @if (user.PhanQuyen == 2)
        {
            <a class="nav-link" href="/user/guestorder">Đơn hàng của khách</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("0"))
        {
            <a class="nav-link active ms-0" href="/tour">Quản lý tour</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("1"))
        {
            <a class="nav-link" href="/hotel">Quản lý khách sạn</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("2"))
        {
            <a class="nav-link" href="/delivery">Quản lý vận chuyển</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("3"))
        {
            <a class="nav-link" href="/restaurant">Quản lý nhà hàng</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("4"))
        {
            <a class="nav-link" href="/destination">Quản lý điểm tham quan</a>
        }
    </nav>
    <hr class="mt-0 mb-4">
    <div class=" bg-white p-5">
        <a href="tour/create">
            <button type="button" class="btn btn-primary mb-3">Thêm Tour</button>
        </a>
        <table id="dataTable" class="table table-bordered  dataTable">
            <thead>
                <tr class="text-center">
                    <th style="text-align: center; width: 5%">Mã tour</th>
                    <th style="text-align: center; width: 20%">Tên tour </th>
                    <th style="text-align: center; width: 5%">Số ngày </th>
                    <th style="text-align: center; width: 10%">Giá tour</th>
                    <th style="text-align: center; width: 10%">Lượt đánh giá </th>
                    <th style="text-align: center; width: 15%">Ngày bắt đầu </th>
                    <th style="text-align: center; width: 15%">Ngày kết thúc </th>
                    <th style="text-align: center; width: 20%">Thao tác </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var tour in tours)
                {
                    <tr>
                        <td class="text-center">@tour.Id</td>
                        <td class="text-center">@tour.TenTour</td>
                        <td class="text-center">@tour.SoNgay</td>
                        <td class="text-center">@tour.GiaTour</td>
                        <td class="text-center">@tour.LuotDanhGia</td>
                        <td class="text-center">@tour.NgayBatDau.ToString()</td>
                        <td class="text-center">@tour.NgayKetThuc.ToString()</td>
                        <td class="text-center">
                            <a href="/tour/edit/@tour.Id" class="btn btn-success">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>