DuLich/DuLichUI/Controllers/Admin/HotelController.cs
using APIIntegration.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace DuLichUI.Controllers.Admin
{
    [Route("~/admin/hotel")]
    [Authorize(Roles = "0")]
    public class HotelController : Controller
    {
        private readonly IHotelAPI _hotelAPI;

        public HotelController(IHotelAPI hotelAPI)
        {
            _hotelAPI = hotelAPI;
        }

        public async Task<IActionResult> Index()
        {
            var hotels = await _hotelAPI.GetAll();
            return View("../Admin/Hotel/Index", hotels);
        }

        [Route("toggle/{id}")]
        public async Task<IActionResult> Toggle(int id)
        {
            await _hotelAPI.Toggle(id, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return RedirectToAction("Index");
        }
    }
}

DuLich/DuLichUI/Controllers/HotelController.cs
using APIIntegration.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ViewModel.Models;
using ViewModel.ModelsView;

namespace DuLichUI.Controllers
{
    [Authorize]
    public class HotelController : Controller
    {
        private IHotelAPI _hotelAPI;
        private IUserAPI _userAPI;

        public HotelController(IHotelAPI hotelAPI, IUserAPI userAPI)
        {
            _hotelAPI = hotelAPI;
            _userAPI = userAPI;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var id = HttpContext.Session.GetString("UserId");
                var hotels = await _hotelAPI.GetKhachSanByOwner(int.Parse(id), "Bearer " + HttpContext.Session.GetString("BearerToken"));
                ViewData["hotels"] = hotels;
                var temp = HttpContext.Session.GetString("User");
                if (temp != null)
                {
                    var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                    var x = await _userAPI.GetById(user.Id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
                    ViewData["user"] = x;
                }
                return View();
            }
            catch
            {
                ViewData["hotels"] = new List<KhachSan>();
                return View();
            }
        }

        public async Task<IActionResult> Booking(int id)
        {
            var hotel = await _hotelAPI.GetById(id);
            if (!hotel.TrangThai)
            {
                return Redirect("/hotel/list");
            }
            var temp = HttpContext.Session.GetString("User");
            if (temp != null)
            {
                var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                var x = await _userAPI.GetById(user.Id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
                ViewData["user"] = x;
            }
            return View(hotel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateBooking([FromForm] DatKhachSanVM request)
        {
            var hotel = await _hotelAPI.GetById(request.IdKhachSans);
            if (!hotel.TrangThai)
            {
                return Redirect("/hotel/list?order=false");
            }
            var temp = HttpContext.Session.GetString("User");
            if (temp != null)
            {
                var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                request.IdNguoiDungs = user.Id;
            }
            await _hotelAPI.DatKhachSan(request, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return Redirect("/hotel/list?order=true");
        }

        public async Task<IActionResult> Create()
        {
            var temp = HttpContext.Session.GetString("User");
            if (temp != null)
            {
                var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                var x = await _userAPI.GetById(user.Id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
                ViewData["user"] = x;
            }
            return View(new KhachSanVM());
        }

        public async Task<IActionResult> Edit(int id)
        {
            var hotel = await _hotelAPI.GetById(id);
            return View(hotel);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
            var hotel = await _hotelAPI.GetById(id);
            if (!hotel.TrangThai)
            {
                return Redirect("/hotel/list");
            }
            ViewData["khachsans"] = await _hotelAPI.GetAll();
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
                ViewData["UserId"] = HttpContext.Session.GetString("UserId");
            return View(hotel);
        }

        [AllowAnonymous]
        public async Task<IActionResult> List()
        {
            var hotels = await _hotelAPI.GetAll();
            return View(hotels);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var hotel = await _hotelAPI.Delete(id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
            return Redirect("/hotel");
        }

        [HttpPost]
        public async Task<IActionResult> EditKhachSan([FromForm] KhachSanVM request)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", request);
            }
            await _hotelAPI.EditKhachSan(request, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return Redirect("/hotel");
        }

        [HttpPost]
        public async Task<IActionResult> CreateKhachSan([FromForm] KhachSanVM request)
        {
            if (!ModelState.IsValid)
            {
                var temp = HttpContext.Session.GetString("User");
                if (temp != null)
                {
                    var user = Newtonsoft.Json.JsonConvert.DeserializeObject<NguoiDung>(temp);
                    var x = await _userAPI.GetById(user.Id, "Bearer " + HttpContext.Session.GetString("BearerToken"));
                    ViewData["user"] = x;
                }
                return View("Create", request);
            }
            await _hotelAPI.CreateKhachSan(request, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return Redirect("/hotel");
        }

        [HttpPost]
        public async Task<IActionResult> CreateBinhLuan([FromForm] BinhLuanKhachSanVM request)
        {
            await _hotelAPI.BinhLuanKhachSan(request, "Bearer " + HttpContext.Session.GetString("BearerToken"));

            return Redirect("/hotel/detail/" + request.IdKhachSan);
        }
    }
}

DuLich/DuLichUI/Views/Hotel/Booking.cshtml
@using ViewModel.Models;
@model KhachSan;

@{
    ViewData["Title"] = "Đặt nhà hàng";
    var user = ViewData["user"] as NguoiDung;
}

<nav class="breadcrumb-nav d-flex align-items-center" aria-label="breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="under" href="/">Home</a></li>
            <li class="breadcrumb-item"><a class="under" href="/hotel/list">Khách sạn</a></li>
        </ol>
    </div>
</nav>
<div class="page-content">
    <div class="container">
        <div class="row">
            <aside class="sidebar col-lg-3 order-1 order-lg-0">
                <div class="sidebar__content js-sticky-top">
                    <section class="sidebar__card card">
                        <div class="sidebar__card-title">
                            <h4 class="card-title mb-1">@Model?.TenKhachSan</h4>
                            <ul class="sidebar__card-meta d-flex align-items-center">
                                <li>
                                    <div class="rating">
                                        <select class="js-rating-stat" data-current-rating="@Model?.DanhGia">
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                        </select>
                                    </div>
                                </li>
                                <li class="likes ml-auto text-nowrap"><i class="mr-1 icon icon-thumbs-up"></i><span>@(Model?.DanhGia * 2)/10</span></li>
                            </ul>
                            <hr class="my-3 mt-2" />
                        </div>
                        <ul class="sidebar__payment">
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Chủ dịch vụ</div>
                                <ul>
                                    <li>@Model.NguoiDung.HoTen</li>
                                </ul>
                            </li>
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Địa chỉ</div>
                                <ul>
                                    <li>@Model.DiaChi</li>
                                </ul>
                            </li>
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Mô tả</div>
                                <ul>
                                    <li>@Model?.MoTaKhachSan</li>
                                </ul>
                            </li>
                        </ul>
                        <hr class="mt-2">
                        <ul class="sidebar__payment-total">
                            <li class="h4 fw-bold f-primary mb-0">Giá: @Model.Gia VND</li>
                        </ul>
                    </section>
                </div>
            </aside>
            <div class="col-lg-9 d-flex" id="barba-wrapper">
                <div class="barba-container">
                    <div class="booking-card card">
                        <div class="card-body">
                            <div class="booking-card__title">
                                <h2>Thông tin đặt hàng</h2>
                                <hr class="mb-4">
                            </div>
                            <form class="booking-card__form" asp-action="CreateBooking" asp-controller="Hotel" method="POST">
                                <input hidden name="IdKhachSans" value="@Model.Id" />
                                <div class="row pad-lg-20">
                                    <div class="form-group col-12 col-lg-6">
                                        <label asp-for="@user.HoTen">Họ và tên</label>
                                        <input class="form-control" asp-for="@user.HoTen" readonly/>
                                    </div>
                                    <div class="form-group col-12 col-lg-6 col-xl-4">
                                        <label asp-for="@user.Sdt">Số điện thoại</label>
                                        <input class="form-control" asp-for="@user.Sdt" readonly />
                                    </div>
                                    <div class="form-group col-12 col-lg-6 col-xl-4">
                                        <label asp-for="@user.Email"></label>
                                        <input class="form-control" asp-for="@user.Email" readonly />
                                    </div>
                                    <div class="form-group col-12 col-lg-6 col-xl-4">
                                        <label asp-for="@user.NoiO">Nơi ở</label>
                                        <input class="form-control" asp-for="@user.NoiO" readonly />
                                    </div>
                                    <div class="form-group col-12 col-lg-6 col-xl-4">
                                        <label asp-for="@user.CCCD">Căn cước công dân</label>
                                        <input class="form-control" asp-for="@user.CCCD" readonly />
                                    </div>
                                    <div class="form-group col-12 col-lg-6 col-xl-4">
                                        <label>Ngày nhận</label>
                                        <input class="form-control" name="NgayNhan" type="datetime-local" required/>
                                    </div>
                                    <div class="form-group col-12 col-lg-6 col-xl-4">
                                        <label>Ngày trả</label>
                                        <input class="form-control" name="NgayTra" type="datetime-local" required />
                                    </div>
                                </div>
                                <div class="d-flex">
                                    <button class="btn btn-secondary btn--round mx-auto ml-sm-0" type="submit">
                                        Booking
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <button class="btn btn-primary btn-nav btn-nav--up js-scroll-up" type="button"><i class="fa fa-angle-up"></i></button>
</div>

DuLich/DuLichUI/Views/Hotel/Create.cshtml
@using ViewModel.Models;
@using ViewModel.ModelsView;
@model KhachSanVM;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Tạo khách sạn";
    NguoiDung user = ViewData["user"] as NguoiDung;
}
<style>
    body {
        margin-top: 20px;
        background-color: #f2f6fc;
        color: #69707a;
    }

    .img-account-profile {
        height: 10rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }

        .card .card-header {
            font-weight: 500;
        }

    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }

    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }

    .form-control, .dataTable-input {
        display: block;
        width: 100%;
        padding: 0.875rem 1.125rem;
        font-size: 0.875rem;
        font-weight: 400;
        line-height: 1;
        color: #69707a;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #c5ccd6;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.35rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }

    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }
</style>
<div class="container-xxl px-4 mt-4">
    <a href="/hotel"><button type="button" class="btn btn-primary mb-3">Quay lại</button></a>
    <hr class="mt-0 mb-4">
    <div class="">
        <div class="card mb-4">
            <div class="card-header">Chi tiết khách sạn</div>
            <div class="card-body">
                <form asp-action="CreateKhachSan" asp-controller="Hotel" method="post" enctype="multipart/form-data">
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Ảnh đại diện</label>
                            <input asp-for="@Model.AnhDaiDien" />
                        </div>
                    </div>
                    <input hidden name="chuDichVu" value="@user.Id"/>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-4">
                            <label  class="small mb-1">Tên khách sạn</label>
                            <input  class="form-control" asp-for="@Model.TenKhachSan"/>
                        </div>
                        <div class="col-md-4">
                            <label class="small mb-1">Địa chỉ</label>
                            <input class="form-control" asp-for="@Model.DiaChi" />
                        </div>
                        <div class="col-md-4">
                            <label class="small mb-1">Giá dịch vụ</label>
                            <input class="form-control" asp-for="@Model.Gia" />
                        </div>
                    </div>
                    <div class="row gx-3 mb-3">
                        <div class="col-md-6">
                            <label class="small mb-1">Mô tả</label>
                            <textarea class="form-control" asp-for="@Model.MoTaKhachSan"></textarea>
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1">Chi tiết</label>
                            <textarea class="form-control" asp-for="@Model.ChiTietKhachSan"></textarea>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Tạo mới</button>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#loader').addClass('d-none');
        });
    </script>
}

DuLich/DuLichUI/Views/Hotel/Edit.cshtml
@using ViewModel.Models;
@model KhachSan;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Cập nhật khách sạn";
    NguoiDung user = ViewData["user"] as NguoiDung;
}
<style>
    body {
        margin-top: 20px;
        background-color: #f2f6fc;
        color: #69707a;
    }

    .img-account-profile {
        height: 10rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }

        .card .card-header {
            font-weight: 500;
        }

    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }

    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }

    .form-control, .dataTable-input {
        display: block;
        width: 100%;
        padding: 0.875rem 1.125rem;
        font-size: 0.875rem;
        font-weight: 400;
        line-height: 1;
        color: #69707a;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #c5ccd6;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.35rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }

    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }
</style>
<div class="container-xxl px-4 mt-4">
    <a href="/hotel"><button type="button" class="btn btn-primary mb-3">Quay lại</button></a>
    <hr class="mt-0 mb-4">
    <div class="row">
        <div class="col-xl-4">
            <div class="card mb-4 mb-xl-0">
                <div class="card-header">Ảnh minh hoạ</div>
                <div class="card-body text-center">
                    <img class="img-account-profile rounded-circle mb-2" src="@Model?.AnhDaiDien" alt="">
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <div class="card mb-4">
                <div class="card-header">Chi tiết khách sạn</div>
                <div class="card-body">
                    <form asp-action="EditKhachSan" asp-controller="Hotel" method="post" enctype="multipart/form-data">
                        <div class="row gx-3 mb-3">
                            <div class="col-md-6">
                                <label class="small mb-1">Ảnh minh hoạ</label>
                                <input type="file" name="AnhDaiDien" />
                            </div>
                        </div>
                        <input hidden name="chuDichVu" value="@Model.ChuDichVu" />
                        <input hidden name="IdKS" value="@Model.Id" />
                        <div class="row gx-3 mb-3">
                            <div class="col-md-4">
                                <label class="small mb-1">Tên khách sạn</label>
                                <input class="form-control" asp-for="@Model.TenKhachSan" />
                            </div>
                            <div class="col-md-4">
                                <label class="small mb-1">Địa chỉ</label>
                                <input class="form-control" asp-for="@Model.DiaChi" />
                            </div>
                            <div class="col-md-4">
                                <label class="small mb-1">Giá dịch vụ</label>
                                <input class="form-control" asp-for="@Model.Gia" />
                            </div>
                        </div>
                        <div class="row gx-3 mb-3">
                            <div class="col-md-6">
                                <label class="small mb-1">Mô tả</label>
                                <textarea class="form-control" asp-for="@Model.MoTaKhachSan"></textarea>
                            </div>
                            <div class="col-md-6">
                                <label class="small mb-1">Chi tiết</label>
                                <textarea class="form-control" asp-for="@Model.ChiTietKhachSan"></textarea>
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">Cập nhật</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#loader').addClass('d-none');
        });
    </script>
}

DuLich/DuLichUI/Views/Hotel/Index.cshtml
@using ViewModel.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Quản lý khách sạn";
    List<KhachSan> dtqs = (List<KhachSan>)ViewData["hotels"];
    NguoiDung user = ViewData["user"] as NguoiDung;
}
<div class="container-xl px-4 mt-4">
    <!-- Account page navigation-->
    <nav class="nav nav-borders">
        <a class="nav-link" href="/user">Profile</a>
        <a class="nav-link" href="/user/order">Đơn hàng của tôi</a>
        @if (user.PhanQuyen == 2)
        {
            <a class="nav-link" href="/user/guestorder">Đơn hàng của khách</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("0"))
        {
            <a class="nav-link" href="/tour">Quản lý tour</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("1"))
        {
            <a class="nav-link active ms-0" href="/hotel">Quản lý khách sạn</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("2"))
        {
            <a class="nav-link" href="/delivery">Quản lý vận chuyển</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("3"))
        {
            <a class="nav-link" href="/restaurant">Quản lý nhà hàng</a>
        }
        @if (user.PhanQuyen == 2 && user.DanhSachDichVu.Contains("4"))
        {
            <a class="nav-link" href="/destination">Quản lý điểm tham quan</a>
        }
    </nav>
    <hr class="mt-0 mb-4">
    <div class=" bg-white p-5">
        <a href="/hotel/create">
            <button type="button" class="btn btn-primary mb-3">Thêm khách sạn</button>
        </a>
        <table id="dataTable" class="table table-bordered  dataTable">
            <thead>
                <tr class="text-center">
                    <th style="text-align: center; width: 5%">Mã</th>
                    <th style="text-align: center; width: 20%">Tên khách sạn </th>
                    <th style="text-align: center; width: 5%">Địa chỉ </th>
                    <th style="text-align: center; width: 10%">Giá</th>
                    <th style="text-align: center; width: 10%">Đánh giá </th>
                    <th style="text-align: center; width: 20%">Thao tác </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var dtq in dtqs)
                {
                    <tr>
                        <td class="text-center">@dtq.Id</td>
                        <td class="text-center">@dtq.TenKhachSan</td>
                        <td class="text-center">@dtq.DiaChi</td>
                        <td class="text-center">@dtq.Gia</td>
                        <td class="text-center">@dtq.DanhGia</td>
                        <td class="text-center">
                            <a href="/hotel/edit/@dtq.Id" class="btn btn-success">Edit</a>
                            <a href="/hotel/delete/@dtq.Id" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>